version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - next_build:/app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/quiz_app.db:/app/instance/app.db
    environment:
      - DATABASE_URL=sqlite:///app/instance/app.db
      - SECRET_KEY=your-secret-key-here
      - OPENAI_API_KEY=your-openai-api-key-here

  adminer:
    build:
      context: ./docker/adminer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=backend
      - ADMINER_DESIGN=pepa-linha
    volumes:
      - ./backend/quiz_app.db:/app/instance/app.db
    depends_on:
      - backend

volumes:
  postgres_data:
  next_build:

networks:
  app-network:
    driver: bridge 